"""add_reservation_fields_and_inputs

Revision ID: b18c1ac4fa84
Revises: 9424e9e75364
Create Date: 2026-02-13 15:01:06.907621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18c1ac4fa84'
down_revision = '9424e9e75364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('timebox_sec', sa.BIGINT(), nullable=True))
    op.add_column('runs', sa.Column('min_reliability_score', sa.FLOAT(), nullable=True))
    op.add_column('runs', sa.Column('inputs_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'inputs_json')
    op.drop_column('runs', 'min_reliability_score')
    op.drop_column('runs', 'timebox_sec')
    # ### end Alembic commands ###
