"""add_completed_at_to_runs

Revision ID: 9424e9e75364
Revises: f99a7078ce99
Create Date: 2026-02-13 14:49:27.731873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9424e9e75364'
down_revision = 'f99a7078ce99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'completed_at')
    # ### end Alembic commands ###
